metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.11.130, mac: '7c:83:34:bb:2b:3a', disk: nvme0n1, network_interface: enp1s0}
        metal1: {ansible_host: 192.168.11.131, mac: '7c:83:34:bb:67:1e', disk: nvme0n1, network_interface: enp1s0}
        metal2: {ansible_host: 192.168.11.132, mac: '7c:83:34:bb:68:62', disk: nvme0n1, network_interface: enp1s0}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.11.133, mac: '7c:83:34:bb:68:7f', disk: nvme0n1, network_interface: enp1s0}
        metal4: {ansible_host: 192.168.11.134, mac: 'e8:ff:1e:d0:0d:5a', disk: nvme0n1, network_interface: enp1s0}

