metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.11.130, mac: '7C:83:34:BB:2B:3A', disk: nvme0n1, network_interface: enp1s0}
        metal1: {ansible_host: 192.168.11.131, mac: '7C:83:34:BB:67:1E', disk: nvme0n1, network_interface: enp1s0}
        metal2: {ansible_host: 192.168.11.132, mac: '7C:83:34:BB:68:62', disk: nvme0n1, network_interface: enp1s0}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.11.133, mac: '7C:b3:34:BB:68:7F', disk: nvme0n1, network_interface: enp1s0}
        metal4: {ansible_host: 192.168.11.134, mac: 'E8:FF:1E:D0:0D:5A', disk: nvme0n1, network_interface: enp1s0}
