metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.10.31, mac: '7C:83:34:BB:2B:3A', disk: nvme0n1, network_interface: enp1s0}
        metal1: {ansible_host: 192.168.10.32, mac: '7C:83:34:BB:67:1E', disk: nvme0n1, network_interface: enp1s0}
        metal2: {ansible_host: 192.168.10.33, mac: '7C:83:34:BB:68:62', disk: nvme0n1, network_interface: enp1s0}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.10.34, mac: '7C:b3:34:BB:68:7F', disk: nvme0n1, network_interface: enp1s0}
